#-----------------------------------------------------------------------------------------------------------------------
# This script reads computer names from DeleteFromAD.txt
# and deletes them.
# Put DeleteFromAD.txt in the same folder as this script when you run it.
# The Active Directory Powershell Commandlet is required.
# Instructions to add the AD commandlet can be found here:
# http://blogs.msdn.com/b/rkramesh/archive/2012/01/17/how-to-add-active-directory-module-in-powershell-in-windows-7.aspx
# 02/12/2015 David Culp
#-----------------------------------------------------------------------------------------------------------------------

#Assign text values to variable
$CompsToDelete = Get-Content .\DeleteFromAD.txt

#Run loop to delete
Foreach ($Comp in $CompsToDelete) {
Remove-ADComputer -Identity $Comp
echo "Deleted $Comp..."
}
Echo "All Done!"
# SIG # Begin signature block
# MIINJQYJKoZIhvcNAQcCoIINFjCCDRICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU1lOFtXDw3oXPLwSkjKqjmWnC
# 2pGgggqgMIIEcjCCA9ugAwIBAgIEByc+2TANBgkqhkiG9w0BAQUFADB1MQswCQYD
# VQQGEwJVUzEYMBYGA1UEChMPR1RFIENvcnBvcmF0aW9uMScwJQYDVQQLEx5HVEUg
# Q3liZXJUcnVzdCBTb2x1dGlvbnMsIEluYy4xIzAhBgNVBAMTGkdURSBDeWJlclRy
# dXN0IEdsb2JhbCBSb290MB4XDTA5MDcwODEzMDUzMloXDTE4MDcwODEzMDQzNFow
# QDETMBEGCgmSJomT8ixkARkWA2VkdTEXMBUGCgmSJomT8ixkARkWB2xpYmVydHkx
# EDAOBgNVBAMTB0xVUEtJMDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQCwFk850vIW/bgTwimgb0ZTVIzwOCT8YuXDs2m6P3KzlPG1kXCUxokMbxS9tque
# QrOlsgUyxZzSIzqvXGVWi7E/SnKrIs5n0PStsGoP+dQM95AwSpwtC3/gEvl/HdK+
# Vtkd4/laodheKy5fYXUBTOY2Lbhvi05aWDqbn+QZzazm0385TCFfShJEUOkgk0Wc
# N7QITDpymHGFDuBhgTrhOyyB7D8wPxx9zzWqrcIKXZZ3S5IPnBevwTY0M4Z4flUN
# TJ9Xj+4lxxa8W8XII4mp/r2BXsd6mfV1Fqw3dkp3hsi39XRinHynex9S3N23o84c
# y8H8LSMR5MgNdMcBG5g+GRsNAgMBAAGjggG+MIIBujASBgNVHRMBAf8ECDAGAQH/
# AgEAMIGhBgNVHSAEgZkwgZYwSQYKKwYBBAGCNw0CAzA7MDkGCCsGAQUFBwIBFi1o
# dHRwOi8vY3liZXJ0cnVzdC5vbW5pcm9vdC5jb20vcmVwb3NpdG9yeS5jZm0wSQYK
# KwYBBAGCNwIBDjA7MDkGCCsGAQUFBwIBFi1odHRwOi8vY3liZXJ0cnVzdC5vbW5p
# cm9vdC5jb20vcmVwb3NpdG9yeS5jZm0wDgYDVR0PAQH/BAQDAgGGMIGJBgNVHSME
# gYEwf6F5pHcwdTELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD0dURSBDb3Jwb3JhdGlv
# bjEnMCUGA1UECxMeR1RFIEN5YmVyVHJ1c3QgU29sdXRpb25zLCBJbmMuMSMwIQYD
# VQQDExpHVEUgQ3liZXJUcnVzdCBHbG9iYWwgUm9vdIICAaUwRQYDVR0fBD4wPDA6
# oDigNoY0aHR0cDovL3d3dy5wdWJsaWMtdHJ1c3QuY29tL2NnaS1iaW4vQ1JMLzIw
# MTgvY2RwLmNybDAdBgNVHQ4EFgQUOPhrrsAwJVP069peSBBOYhgSu4kwDQYJKoZI
# hvcNAQEFBQADgYEAey+FF3DAGKLu7eiUmwKvtbg5w7UWY7mi4sEfimVlGqqcfa1/
# edtLfyTMv/2Qmmq7d5hBUvIlemJLFHKYL5jMguKx8blzWLj2lG8WDn78ObsZ9Or9
# /OFqFW3Qqq9FMTBX5BuDIQWOmCLD67en6tniq7ABuJJgDXTcnHBK1KG0LhAwggYm
# MIIFDqADAgECAgpjV7bpAAAAAA7BMA0GCSqGSIb3DQEBBQUAMEAxEzARBgoJkiaJ
# k/IsZAEZFgNlZHUxFzAVBgoJkiaJk/IsZAEZFgdsaWJlcnR5MRAwDgYDVQQDEwdM
# VVBLSTAxMB4XDTE1MDIxMjE0MTkxM1oXDTE2MDIxMjE0MTkxM1oweTETMBEGCgmS
# JomT8ixkARkWA2VkdTEXMBUGCgmSJomT8ixkARkWB2xpYmVydHkxGjAYBgoJkiaJ
# k/IsZAEZFgpVbml2ZXJzaXR5MQwwCgYDVQQLEwNGU0ExDjAMBgNVBAsTBVVzZXJz
# MQ8wDQYDVQQDEwZkYWN1bHAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDBBkc6JoT37a0u+VWWVbfSuija7VH6bHShupklzEQvbmt0ZFXkSNYJ9hpO3pbJ
# uSauYm+Jqu3HKRUaW4Q2xAuge7T+aCT5eGPiVi/uQeq2mLp2jNahtYNtEOBJ2mtE
# AmS2BAh/A0pG1cyE4SYDWtOWVVte9xMHYV/EvBkX9DA2k/HOp9Dc3im+12ZQVKvl
# cNgnkKkJGO+LIiZdJlKm3UANAUrl0GbRjsbPPSoyZ2LwT27KAkCtWSJJQbGUR3Sl
# DmLUFZ72gaCb9NXmOVldA1vj2Uu+UthrSxrgpq7MSXCJ2czLhFPy5pAeBWZNS2eN
# ZdT9nFmSp0qP08rR6tzH9u1dAgMBAAGjggLnMIIC4zA7BgkrBgEEAYI3FQcELjAs
# BiQrBgEEAYI3FQiCifs2h+2/NPWPHoH65jCF26haFp2xSIf55lQCAWQCAQMwEwYD
# VR0lBAwwCgYIKwYBBQUHAwMwDgYDVR0PAQH/BAQDAgeAMBsGCSsGAQQBgjcVCgQO
# MAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFNQ9n+PIp4UwVbNrkP3Z08VnzagDMB8G
# A1UdIwQYMBaAFDj4a67AMCVT9OvaXkgQTmIYEruJMIHtBgNVHR8EgeUwgeIwgd+g
# gdyggdmGga5sZGFwOi8vL0NOPUxVUEtJMDEsQ049bHVwa2kwMSxDTj1DRFAsQ049
# UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJh
# dGlvbixEQz1saWJlcnR5LERDPWVkdT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0
# P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGJmh0dHA6Ly93
# d3cubGliZXJ0eS5lZHUvcGtpL0xVUEtJMDEuY3JsMIIBAQYIKwYBBQUHAQEEgfQw
# gfEwgaYGCCsGAQUFBzAChoGZbGRhcDovLy9DTj1MVVBLSTAxLENOPUFJQSxDTj1Q
# dWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0
# aW9uLERDPWxpYmVydHksREM9ZWR1P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RD
# bGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MEYGCCsGAQUFBzAChjpodHRwOi8v
# d3d3LmxpYmVydHkuZWR1L3BraS9sdXBraTAxLmxpYmVydHkuZWR1X0xVUEtJMDEu
# Y3J0MC0GA1UdEQQmMCSgIgYKKwYBBAGCNxQCA6AUDBJkYWN1bHBAbGliZXJ0eS5l
# ZHUwDQYJKoZIhvcNAQEFBQADggEBAJV84QJ6Wh534nrv+NYmDEzPYlyQ7VnDz5He
# FBon0SuXv5iINTEigzXj9mIOFqc+T1wotBd9N//t93jwRx8fVMyc16arEcFKXbU3
# WW1BgeTmf2xfcy1IEH3GaVKkafKZ90n68v7U3QPIm8xtacstbuD1jdAvYkIotNzc
# CT2b0sk1iLClvWGYLZK8l/c4hoS0awbhG53XERbHmcJGC3NBVv9qExWQj+DaWXQo
# yU1x9+TNvROrcv7u0/EjJWSoDwL4AziDvf/vFt3MJWuWsMN0UeLg1DeBGSIhjYr8
# 4LGHfhj7t3cwzyzcmt5mbiE2Iw80cNDDsXnUP96Arp7d1auIK4ExggHvMIIB6wIB
# ATBOMEAxEzARBgoJkiaJk/IsZAEZFgNlZHUxFzAVBgoJkiaJk/IsZAEZFgdsaWJl
# cnR5MRAwDgYDVQQDEwdMVVBLSTAxAgpjV7bpAAAAAA7BMAkGBSsOAwIaBQCgeDAY
# BgorBgEEAYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3
# AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEW
# BBTtp/r5AlKXXzzz4JKayjgd0A/a0DANBgkqhkiG9w0BAQEFAASCAQDAcRhNEJm1
# AoidSlRuXhQJ8fk58PKWAO7jQYFn7eX0CmSPiRtLUimBEesOpVj2IbQWbsXS3Bic
# jlYV0QtiwNt131o1rXQ9hRxaZU2BdurdpJeF3I+5ptAzUbntCYDWqKqRbgK8ZyrH
# UfByXJLsqtk5/QLkB3KErqtjZyQJ5Di8j6g41CTAF4jAVqiq2rG4vBzWtlrOt+EA
# EmK+B1tVy3D2Tf2P20ceYWpJ/B5CQeXMMjnnp87LjgVwV71tja+a42tUh/pwg76Q
# 9eFBQkxmCnMcPVdjQgBGObT+HEgHBF+G8vjOUua7bRGMqB1aJ07ugJg37mcCCqKT
# Exb5az/ObgE4
# SIG # End signature block
